### ISSUE TITLE
Unable to run Android Service "WorkManager is not initialized properly"

### ISSUE THREAD

**Issue by ThanyaLeif** [microsoft/accessibility-insights-for-android-service#150]
## Describe the bug

Got a fatal exception when trying to run Accessibility Insights for Android service: `WorkManager is not initialized properly`

**To Reproduce**

1. Open the AI for Android Service on Android Studio
2. Run app (Shift + F10)
3. Wait until the app gets installed in the emulator
4. Open the Settings app in the emulator.
5. Scroll down and select Accessibility
6. Select "Accessibility Insights for Android Service" under Downloaded services
7. Toggle on Use service to enable the service
8. Select Allow on the resulting dialog to grant the necessary permissions
9. The service crashes

## Expected behavior

An "Exposing sensitive info during casting/recording" dialog should appear. And the app should start running after hitting the button "Start now"

## Screenshots

<img width="229" alt="image" src="https://user-images.githubusercontent.com/32908302/156272787-2b731d1e-4a5f-45eb-9260-a870545b58ee.png">

## Additional context
Using the latest released version of the service (v2.0.0) worked. 
The problem was introduced in the last few months after that.

**Comment by ferBonnin** [comment]
Reviewed with Peter, this is blocking the release of the service. Would also be good to confirm this is not blocking release of the client.

**Comment by DaveTryon** [comment]
Using `git bisect`, I've confirmed that this was introduced in #130. I've also found that it only occurs in API versions 29 or greater. Working now to understand the root cause and an appropriate fix.

**Comment by DaveTryon** [comment]
The Exception being thrown has the following message:
```
java.lang.RuntimeException: Unable to get provider com.microsoft.accessibilityinsightsforandroidservice.AccessibilityInsightsContentProvider: 
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled
WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point,
and your Application does not implement Configuration.Provider.
```

This gets thrown when we call `WorkManager.getInstance` from `TempFileProvider`'s [constructor](https://github.com/microsoft/accessibility-insights-for-android-service/blob/main/AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/TempFileProvider.java#L34). 

The problem goes away if I remove the AndroidManifest.xml [lines](https://github.com/microsoft/accessibility-insights-for-android-service/blob/main/AccessibilityInsightsForAndroidService/app/src/main/AndroidManifest.xml#L54-L60) that enable ADB, so our manifest changes apparently have an unintended side effect of disabling the default initialization of `WorkManager`. [These docs](https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration#remove-default) describe how to intentionally disable the default initialization of `WorkManager`, but I haven't yet been able to find a way to intentionally _enable_ them.

Avenues to explore if we can't find a manifest-driven way to fix this
- Add a class that explicitly calls `WorkManager.initiallize` exactly once for each context
- Add support for `Configuration.Provider1 to the application.
- Back out the commit that added the dependency on `WorkManager`. That is a loss of functionality, but is at par with what we are currently shipping

**Comment by DaveTryon** [comment]
This was fixed in #152 and #153.

@ThanyaLeif, can you please confirm and close this out?
